"""Init DB

Revision ID: cf51136d1430
Revises: 
Create Date: 2026-09-27 19:46:01.378386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf51136d1430'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_standards',
    sa.Column('standard_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('standard_code')
    )
    op.create_table('delay_reason_lookup',
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reason_code')
    )
    op.create_table('mines',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('mine_type', sa.String(), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('boundary_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('lease_area_ha', sa.Numeric(), nullable=True),
    sa.Column('baseline_production_tpd', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mine_id')
    )
    # GeoAlchemy2 automatically creates gist indexes for geometries
    op.create_table('model_registry',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('cv_metric_value', sa.Numeric(), nullable=True),
    sa.Column('trained_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('model_name', 'version')
    )
    op.create_table('sdg_mappings',
    sa.Column('sdg_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('relevance_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sdg_number')
    )
    op.create_table('equipment',
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_index(op.f('ix_equipment_mine_id'), 'equipment', ['mine_id'], unique=False)
    op.create_table('geochem_samples',
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('mno_pct', sa.Numeric(), nullable=True),
    sa.Column('fe2o3_pct', sa.Numeric(), nullable=True),
    sa.Column('sample_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    # GeoAlchemy2 automatically creates gist indexes for geometries
    op.create_index(op.f('ix_geochem_samples_mine_id'), 'geochem_samples', ['mine_id'], unique=False)
    op.create_table('grade_polygons',
    sa.Column('polygon_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('grade_band', sa.String(), nullable=True),
    sa.Column('avg_mno_pct', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('polygon_id')
    )
    # GeoAlchemy2 automatically creates gist indexes for geometries
    op.create_index(op.f('ix_grade_polygons_mine_id'), 'grade_polygons', ['mine_id'], unique=False)
    op.create_table('mine_compliance_status',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('standard_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_audit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.ForeignKeyConstraint(['standard_code'], ['compliance_standards.standard_code'], ),
    sa.PrimaryKeyConstraint('mine_id', 'standard_code')
    )
    op.create_table('price_tiers',
    sa.Column('tier_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('grade_band', sa.String(), nullable=True),
    sa.Column('price_per_tonne', sa.Numeric(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('tier_id')
    )
    op.create_index(op.f('ix_price_tiers_mine_id'), 'price_tiers', ['mine_id'], unique=False)
    op.create_table('production_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('actual_tonnage', sa.Numeric(), nullable=True),
    sa.Column('target_tonnage', sa.Numeric(), nullable=True),
    sa.Column('forecast_tonnage', sa.Numeric(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_production_records_mine_period', 'production_records', ['mine_id', 'period'], unique=False)
    op.create_index(op.f('ix_production_records_mine_id'), 'production_records', ['mine_id'], unique=False)
    op.create_table('prospectivity_zones',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geological_potential_score', sa.Numeric(), nullable=True),
    sa.Column('accessible_ore_score', sa.Numeric(), nullable=True),
    sa.Column('recoverable_ore_score', sa.Numeric(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('zone_id')
    )
    # GeoAlchemy2 automatically creates gist indexes for geometries
    op.create_index(op.f('ix_prospectivity_zones_mine_id'), 'prospectivity_zones', ['mine_id'], unique=False)
    op.create_table('raster_layers',
    sa.Column('layer_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('layer_type', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('resolution_m', sa.Numeric(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('crs', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('layer_id')
    )
    # GeoAlchemy2 automatically creates gist indexes for geometries
    op.create_index(op.f('ix_raster_layers_mine_id'), 'raster_layers', ['mine_id'], unique=False)
    op.create_table('shortfall_events',
    sa.Column('shortfall_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('target_tonnage', sa.Numeric(), nullable=True),
    sa.Column('forecast_or_actual_tonnage', sa.Numeric(), nullable=True),
    sa.Column('gap_tonnage', sa.Numeric(), nullable=True),
    sa.Column('gap_pct', sa.Numeric(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('is_real_anchor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('shortfall_id')
    )
    op.create_index('idx_shortfall_events_mine_period', 'shortfall_events', ['mine_id', 'period'], unique=False)
    op.create_index(op.f('ix_shortfall_events_mine_id'), 'shortfall_events', ['mine_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('assigned_mine_id', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('value_forecast',
    sa.Column('forecast_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('grade_band', sa.String(), nullable=True),
    sa.Column('forecast_tonnage', sa.Numeric(), nullable=True),
    sa.Column('ex_mine_price_per_tonne', sa.Numeric(), nullable=True),
    sa.Column('forecast_revenue', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index('idx_value_forecast_mine_period', 'value_forecast', ['mine_id', 'period'], unique=False)
    op.create_index(op.f('ix_value_forecast_mine_id'), 'value_forecast', ['mine_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('curr_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('cause_analysis',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('shortfall_id', sa.String(), nullable=True),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('shap_value', sa.Numeric(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shortfall_id'], ['shortfall_events.shortfall_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('corrective_actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('shortfall_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('recommended_change', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_gap_closure_tonnage', sa.Numeric(), nullable=True),
    sa.Column('feasibility_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shortfall_id'], ['shortfall_events.shortfall_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('generated_reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('production_entries',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('actual_output_tonnage', sa.Numeric(), nullable=True),
    sa.Column('target_tonnage_snapshot', sa.Numeric(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reason_notes', sa.String(), nullable=True),
    sa.Column('operating_hours', sa.Numeric(), nullable=True),
    sa.Column('downtime_hours', sa.Numeric(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_production_entries_mine_id'), 'production_entries', ['mine_id'], unique=False)
    op.create_table('blasting_events',
    sa.Column('blast_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=True),
    sa.Column('production_entry_id', sa.String(), nullable=True),
    sa.Column('planned_datetime', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('actual_datetime', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delay_hours', sa.Numeric(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['delay_reason'], ['delay_reason_lookup.reason_code'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.mine_id'], ),
    sa.ForeignKeyConstraint(['production_entry_id'], ['production_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('blast_id')
    )
    op.create_index(op.f('ix_blasting_events_mine_id'), 'blasting_events', ['mine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blasting_events_mine_id'), table_name='blasting_events')
    op.drop_table('blasting_events')
    op.drop_index(op.f('ix_production_entries_mine_id'), table_name='production_entries')
    op.drop_table('production_entries')
    op.drop_table('generated_reports')
    op.drop_table('corrective_actions')
    op.drop_table('cause_analysis')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_value_forecast_mine_id'), table_name='value_forecast')
    op.drop_index('idx_value_forecast_mine_period', table_name='value_forecast')
    op.drop_table('value_forecast')
    op.drop_table('users')
    op.drop_index(op.f('ix_shortfall_events_mine_id'), table_name='shortfall_events')
    op.drop_index('idx_shortfall_events_mine_period', table_name='shortfall_events')
    op.drop_table('shortfall_events')
    op.drop_index(op.f('ix_raster_layers_mine_id'), table_name='raster_layers')
    op.drop_index('idx_raster_layers_bbox', table_name='raster_layers', postgresql_using='gist')
    op.drop_table('raster_layers')
    op.drop_index(op.f('ix_prospectivity_zones_mine_id'), table_name='prospectivity_zones')
    op.drop_index('idx_prospectivity_zones_geom', table_name='prospectivity_zones', postgresql_using='gist')
    op.drop_table('prospectivity_zones')
    op.drop_index(op.f('ix_production_records_mine_id'), table_name='production_records')
    op.drop_index('idx_production_records_mine_period', table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_price_tiers_mine_id'), table_name='price_tiers')
    op.drop_table('price_tiers')
    op.drop_table('mine_compliance_status')
    op.drop_index(op.f('ix_grade_polygons_mine_id'), table_name='grade_polygons')
    op.drop_index('idx_grade_polygons_geom', table_name='grade_polygons', postgresql_using='gist')
    op.drop_table('grade_polygons')
    op.drop_index(op.f('ix_geochem_samples_mine_id'), table_name='geochem_samples')
    op.drop_index('idx_geochem_samples_geom', table_name='geochem_samples', postgresql_using='gist')
    op.drop_table('geochem_samples')
    op.drop_index(op.f('ix_equipment_mine_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('sdg_mappings')
    op.drop_table('model_registry')
    op.drop_index('idx_mines_centroid', table_name='mines', postgresql_using='gist')
    op.drop_index('idx_mines_boundary_geom', table_name='mines', postgresql_using='gist')
    op.drop_table('mines')
    op.drop_table('delay_reason_lookup')
    op.drop_table('compliance_standards')
    # ### end Alembic commands ###
